### ISSUE TITLE
リスト内のlenが0になったら終わらせることがすごいと感動した

### ISSUE THREAD

**Issue by RyuhoFukuda** [C0B21017/ProjExD#2]
https://github.com/C0B21017/ProjExD/blob/5691347a27092964d0a5ffb832cbbb76f246ad6b/ex01/alphabet.py#L28

**Comment by C0B21017** [comment]
while文でリスト内が0じゃないときのみループさせる方がきれいになりますかね？

**Comment by C0B21017** [comment]
感動してもらえてよかったです。ぜひ参考にしてください！
