### ISSUE TITLE
最大挑戦回数を決められていないのでは

### ISSUE THREAD

**Issue by RyuhoFukuda** [C0B21017/ProjExD#3]
https://github.com/C0B21017/ProjExD/blob/5691347a27092964d0a5ffb832cbbb76f246ad6b/ex01/alphabet.py#L20　kaitou関数内のchallengeで、失敗したらすぐ「残念！」とbreakしてしまうが、正解するまで何回からやり直し、そのうえで最大挑戦回数を定めなければいけないと思うのだが、それができていないのでは？と思った。

**Comment by C0B21017** [comment]
確かに最大に挑戦回数を定めているものの、失敗した瞬間にbreakすることから機能していないですね。後で修正しておきます。
