### ISSUE TITLE
=のボタン設定は失敗していない

### ISSUE THREAD

**Issue by RyuhoFukuda** [C0B21017/ProjExD#4]
https://github.com/C0B21017/ProjExD/blob/ac4e5f4d81628ac6966350c582fa3e3eddde0a37/ex02/calc.py#L14
READMEには=のボタン設定が失敗しているため-などの機能が作れなかったとあるが、=のボタン設定自体はSyntaxErrorなどのエラーが起こることを除いて機能しないものではないため、-のボタンは作ることが出来ると思う。eval関数では文字列を数式のように扱えるため、+を-に変えればできるはずです。

**Comment by C0B21017** [comment]
#5　コメント対応後、修正させていただきます。
理由としては、for文のループ変更から修正を行うためです。
