### ISSUE TITLE
ボタン割り振り

### ISSUE THREAD

**Issue by takaemonn** [C0B21017/ProjExD#5]
https://github.com/C0B21017/ProjExD/blob/ac4e5f4d81628ac6966350c582fa3e3eddde0a37/ex02/calc.py#L24
文字列として=, + を入力してgetで読み込む形にすると、rengeの範囲をいちいち変更しなくて済み、機能追加が簡単になると思う。

**Comment by C0B21017** [comment]
コメントありがとうございます。先ほど修正しました。
