### ISSUE TITLE
if文の分岐について

### ISSUE THREAD

**Issue by c0b21033** [C0B21017/ProjExD#7]
https://github.com/C0B21017/ProjExD/blob/6e6bfcc302dabb2e35ebd146b47745e720d3f2b3/ex03/maze.py#L20　20～45行目のifの分岐の部分でifとelseで分けるのではなくifの中で上が押されたかつ、動いた先が壁ではなければ、座標を変えるという処理にすることですっきりと書けると思います。

**Comment by C0B21017** [comment]
ありがとうございます。if文にて"and"を使用することで実現しました。
